FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install -g @angular/cli && npm install

COPY . .

RUN ng build --configuration production

FROM nginx:alpine


RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist/my-angular-app/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
