apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: mohamedelnhas018/anguler-app-backend:1.2
          ports:
            - containerPort: 3000
          
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000         # البورت اللي هيبان داخل الكلاستر
      targetPort: 3000   # البورت جوه الـ Pod
      nodePort: 32000    # البورت اللي هتفتحيه من النود (ممكن تختاري أي رقم من 30000-32767)
  type: NodePort

